Joblanes.Web/Models/ViewModel/CompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace Web.Joblanes.Models.ViewModel
{
    public class CompanyViewModel
    {
        [Required(ErrorMessage = "Company Name is required")]
        [Display(Name = "Company Name")]
        [StringLength(200)]
        public virtual string CompanyName { get; set; } 
        public virtual long Id { get; set; }

        [Display(Name = "Contact Person")]
        [StringLength(150)]
        public virtual string ContactPerson { get; set; }

        [Display(Name = "Designation")]
        [StringLength(50)]
        public virtual string ContactPersonDesignation { get; set; }

        [Required(ErrorMessage = "Contact Mobile is required")]
        [Display(Name = "Contact Mobile")]
        [StringLength(50)]
        public virtual string ContactMobile { get; set; }

        [Required(ErrorMessage = "Contact Email is required")]
        [Display(Name = "Contact Email")]
        [StringLength(50)]
        [EmailAddress(ErrorMessage = "Invalid Email ")]
        public virtual string ContactEmail { get; set; }

        [Display(Name = "Contact Mobile")]
        public virtual byte[] LogoBytes { get; set; }
        //  [NonSerialized]
        private HttpPostedFileBase _logo;

        [DataType(DataType.Upload)]
        [DataMember]
        public HttpPostedFileBase Logo 
        {
            get { return _logo; }
            set { _logo = value; }
        }

        public virtual string UserProfileId { get; set; }

        [Required(ErrorMessage = "Company Type is required")]
        [Display(Name = "Company Type")]
        public virtual long CompanyType { get; set; }

        [Display(Name = "Trade Licence")]
        [StringLength(200)]
        public virtual string TradeLicence { get; set; }

        [Display(Name = "Website")]
        [StringLength(200)]
        public virtual string WebLink { get; set; }

        [Display(Name = "Linkdin Link")]
        [StringLength(200)]
        public virtual string LinkdinLink { get; set; }

        [Display(Name = "Vision")]
        public virtual string Vision { get; set; }

        [Display(Name = "Mission")]
        public virtual string Mission { get; set; }

        [Display(Name = "Description")]
        public virtual string Description { get; set; }

        [Display(Name = "Address")]
        public virtual string Address { get; set; }

        [Display(Name = "Zip")]
        [StringLength(20)]
        //[Range(1000, 9999, ErrorMessage = "The Zip must be 4 characters long.")]  
        public virtual string Zip { get; set; }

        [Display(Name = "Tag Line")]
        public virtual string TagLine { get; set; }

        [Display(Name = "Region")]
        public virtual long Region { get; set; }

        [Display(Name = "Country")]
        public virtual long Country { get; set; }

        [Display(Name = "State")]
        public virtual long? State { get; set; }

        [Display(Name = "City")]
        public virtual long City { get; set; }

        [Display(Name = "Employee Size")]
        public virtual int EmployeeSize { get; set; }

        [Display(Name = "Established Date")]
        public virtual DateTime? EstablishedDate { get; set; }
    }
}

Joblanes.Web/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Office.Interop.Word;
using Model.JobLanes.Dto;
using Model.JobLanes.ViewModel;
using NHibernate;
using Services.Joblanes;
using Services.Joblanes.Helper;
using Web.Joblanes.Helper;
using Web.Joblanes.Models.ViewModel;
using Constants = Web.Joblanes.Context.Constants;
using ImageHelper = Web.Joblanes.Helper.ImageHelper;


namespace Web.Joblanes.Controllers
{
    [Authorize]
    [RedirectingAction]
    public class CompanyController : Controller
    {
        #region Logger
        readonly log4net.ILog _logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        #endregion

        #region Objects/Properties/Services/Dao & Initialization

        //private readonly IWcfUserService _wcfUserService;
        //private readonly ICompanyAdminService _companyAdminService; 
        //private readonly IWebAdminService _webAdminService;
        private readonly CommonHelper _commonHelper;
        private readonly IRegionService _regionSevice;
        private readonly ICountryService _countryService;
        private readonly IStateService _stateService;
        private readonly ICityService _cityService;
        private readonly IOrganizationTypeService _organizationTypeService;
        private readonly IUserService _userService;
        private readonly ICompanyService _companyService;
        private readonly ICompanyDetailsService _companyDetailsService;
        private readonly IJobPostService _jobPostService;
        private readonly IProfileViewService _profileViewService;
        private readonly IJobseekerService _jobseekerService;
        private readonly ICompanyTypeService _companyTypeService;
        private readonly IJobCategoryService _jobCategoryService;
        private readonly IJobTypeService _jobTypeService;
        public CompanyController()
        {
            _commonHelper = new CommonHelper();

            ISession session = NhSessionFactory.OpenSession();
            _regionSevice = new RegionService(session);
            _countryService = new CountryService(session);
            _stateService = new StateService(session);
            _cityService = new CityService(session);
            _organizationTypeService = new OrganizationTypeService(session);
            _userService = new UserService(session);
            _companyService = new CompanyService(session);
            _companyDetailsService = new CompanyDetailsService(session);
            _jobPostService = new JobPostService(session);
            _profileViewService = new ProfileViewService(session);
            _jobseekerService = new JobSeekerService(session);
            _companyTypeService = new CompanyTypeService(session);
            _jobCategoryService= new JobCategoryService(session);
            _jobTypeService= new JobTypeService(session);
            //_companyTypeService = new CompanyService(session);
        }
        #endregion

        #region Company Profile
        [Authorize(Roles = "Employers")]
        public ActionResult Index()
        {
            var company = new CompanyDto();
            try
            {
                var userId = System.Web.HttpContext.Current.User.Identity.GetUserId().ToString();
                company = _companyService.GetCompany(userId);
                if (company == null || !company.CompanyDetailList.Any())
                {
                    ViewBag.ErrorMessage = "Please Add profile information";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = " Profile Load Error.";
            }

            return View(company);
        }
        #endregion

        #region Edit Profile
        [HttpGet]
        [Authorize(Roles = "Employers")]
        public ActionResult EditProfile(int type = 0, string message = "")
        {
            CompanyViewModel data = new CompanyViewModel();
            try
            {

                var userId = System.Web.HttpContext.Current.User.Identity.GetUserId().ToString();
                var company = _companyService.GetCompany(userId);

                if (company != null)
                {
                    data.CompanyName = company.Name;
                    if (company.CompanyType != null)
                    {
                        data.CompanyType = company.CompanyType.Id;
                    }

                    data.ContactEmail = company.ContactEmail;
                    data.ContactMobile = company.ContactMobile;
                    data.ContactPerson = company.ContactPerson;
                    data.ContactPersonDesignation = company.ContactPersonDesignation;
                    data.LogoBytes = company.Logo;
                    data.UserProfileId = company.UserProfile.AspNetUserId;
                    if (company.CompanyDetailList.Any())
                    {
                        var companyDetails = company.CompanyDetailList.FirstOrDefault();
                        if (companyDetails != null)
                        {
                            data.TradeLicence = companyDetails.TradeLicence;
                            data.WebLink = companyDetails.WebLink;
                            data.LinkdinLink = companyDetails.LinkdinLink;
                            data.Vision = companyDetails.Vision;
                            data.Mission = companyDetails.Mission;
                            data.Description = companyDetails.Description;
                            data.Address = companyDetails.Address;
                            data.Zip = companyDetails.Zip;
                            data.EstablishedDate = companyDetails.EstablishedDate;
                            data.EmployeeSize = companyDetails.EmployeeSize;
                            data.Region = companyDetails.Country == null ? 0 : companyDetails.Country.Region.Id;
                            data.Country = companyDetails.Country == null ? 0 : companyDetails.Country.Id;
                            data.State = companyDetails.State != null ? companyDetails.State.Id : 0;
                            data.City = companyDetails.City == null ? 0 : companyDetails.City.Id;
                            data.TagLine = companyDetails.TagLine;
                        }
                    }

                }

                ViewBag.EmployeeSizeList = new SelectList(_commonHelper.LoadEmumToDictionary<Constants.EmployeeSize>(), "Key", "Value").ToList();

                ViewBag.CompanyTypeList = new SelectList(_companyTypeService.LoadCompanyType(EntityStatus.Active), "Id", "Name", data.CompanyType);
                ViewBag.RegionList = new SelectList(_regionSevice.LoadRegion(EntityStatus.Active), "Id", "Name", data.Region);
                ViewBag.CountryList = new SelectList(string.Empty, "Value", "Text");
                ViewBag.StateList = new SelectList(string.Empty, "Value", "Text");
                ViewBag.CityList = new SelectList(string.Empty, "Value", "Text");
                if (data.Region > 0)
                {
                    ViewBag.CountryList = new SelectList(_countryService.LoadCountry(EntityStatus.Active, data.Region), "Id", "Name", data.Country);
                }
                if (data.Country > 0)
                {
                    ViewBag.StateList = new SelectList(_stateService.LoadState(data.Region, data.Country, EntityStatus.Active), "Id", "Name", data.State);
                    ViewBag.CityList = new SelectList(_cityService.LoadCity(data.Region, data.Country, null, EntityStatus.Active), "Id", "Name", data.City);
                }
                if (data.State > 0)
                {
                    ViewBag.CityList = new SelectList(_cityService.LoadCity(data.Region, data.Country, data.State, EntityStatus.Active), "Id", "Name", data.City);
                }
                if (type == 1)
                {
                    ViewBag.SuccessMessage = message;
                }
                else if (type == 2)
                {
                    ViewBag.ErrorMessage = message;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(data);
        }

        [HttpPost]
        [Authorize(Roles = "Employers")]
        public ActionResult EditProfile(CompanyViewModel data)
        {
            try
            {
                if (ModelState.IsValid)
                {


                    var logoUpload = data.Logo;
                    var userId = System.Web.HttpContext.Current.User.Identity.GetUserId().ToString();
                    var company = _companyService.GetCompany(userId);



                    var wcfVm = new CompanyViewModel()
                    {
                        Id = data.Id,
                        CompanyName = data.CompanyName,
                        ContactPerson = data.ContactPerson,
                        ContactPersonDesignation = data.ContactPersonDesignation,
                        ContactEmail = data.ContactEmail,
                        ContactMobile = data.ContactMobile,
                        CompanyType = data.CompanyType,
                        TradeLicence = data.TradeLicence,
                        WebLink = data.WebLink,
                        LinkdinLink = data.LinkdinLink,
                        Vision = data.Vision,
                        Mission = data.Mission,
                        Description = data.Description,
                        Address = data.Address,
                        Zip = data.Zip,
                        Region = data.Region,
                        Country = data.Country,
                        State = data.State ?? 0,
                        City = data.City,
                        TagLine = data.TagLine,

Joblanes.Web/Views/Company/JobDetails.cshtml
@model Model.JobLanes.Dto.JobPostsDto
@{
    ViewBag.Title = "Job Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row" style="padding-right: 10px;">
    <div class="col-md-12">
        <div class="panel panel-primary">
        <div class="panel-heading custom-panel-h"> Job Details</div>
        @{
            if (Model!=null && Model.Id>0)
            {
                  <div class="panel-body">
                    <table class="table table-bordered table-hover table-responsive table-striped">
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Title </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.JobTitle)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Job Category </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.JobCategory.Name)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Job Type </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.JobType.Name)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>No Of Vacancies </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.NoOfVacancies)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Receive CV/Resume Option</strong>
                        </td>
                        <td style="text-align: left">
                            @{
                                if (Model.IsOnlineCv != null && (bool) Model.IsOnlineCv)
                                {
                                    <span>Online&nbsp;&nbsp;</span>
                                }
                                if (Model.IsEmailCv != null && (bool) Model.IsEmailCv)
                                {
                                    <span>By Email&nbsp;&nbsp;</span>
                                }
                                if (Model.IsHardCopy != null && (bool) Model.IsHardCopy)
                                {
                                    <span>Hard Copy&nbsp;&nbsp;</span>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Enclose photograph with CV?</strong>
                        </td>
                        <td style="text-align: left">
                            @{
                                if (Model.IsPhotographAttach != null && (bool) Model.IsPhotographAttach)
                                {
                                    <span>Yes&nbsp;&nbsp;</span>
                                }
                                else
                                {
                                    <span>No&nbsp;&nbsp;</span>
                                }

                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Apply Instruction </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.ApplyInstruction)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Deadline </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.DeadLine)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Display</strong>
                        </td>
                        <td style="text-align: left">
                            @{
                                if (Model.IsDisplayCompanyName != null && (bool) Model.IsDisplayCompanyName)
                                {
                                    <span>Company Name,&nbsp;&nbsp;</span>
                                }
                                if (Model.IsDisplayCompanyBusiness != null && (bool) Model.IsDisplayCompanyBusiness)
                                {
                                    <span>Company Business&nbsp;&nbsp;</span>
                                }
                                if (Model.IsDisplayCompanyAddress != null && (bool) Model.IsDisplayCompanyAddress)
                                {
                                    <span>Company Address&nbsp;&nbsp;</span>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Age Range</strong>
                        </td>
                        <td style="text-align: left">
                            @{
                                if (Model.AgeRangeFrom == null && Model.AgeRangeTo==null)
                                {
                                    <span>Not Required</span>
                                }
                                else
                                {
                                     if (Model.AgeRangeFrom!=null)
                                    {
                                        <span>From @Model.AgeRangeFrom</span>
                                    }
                                    if (Model.AgeRangeTo != null)
                                    {
                                        <span>To @Model.AgeRangeTo</span>
                                    }
                                }
                               
                            }
                            
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Gender</strong>
                        </td>
                        <td style="text-align: left">
                            @{
                                if (Model.IsMale != null && (bool) Model.IsMale)
                                {
                                    <span>Male Only&nbsp;&nbsp;</span>
                                }
                                else if (Model.IsFemale != null && (bool) Model.IsFemale)
                                {
                                    <span>Female Only&nbsp;&nbsp;</span>
                                }
                                else
                                {
                                    <span>All</span>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Job Level</strong>
                        </td>
                        <td style="text-align: left">
                            @{
                                if (Model.JobLevel != null && Model.JobLevel == 1)
                                {
                                    <span>Entry Level Job&nbsp;&nbsp;</span>
                                }
                                else if (Model.JobLevel != null && Model.JobLevel == 2)
                                {
                                    <span>Mid/Managerial Level Job&nbsp;&nbsp;</span>
                                }
                                else
                                {
                                    <span>Top Level Job</span>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Educational Qualification </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.EducationalQualification)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Job Description </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.Raw(Html.Encode(Model.JobDescription).Replace("\n", "<br />"))
                           
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Additional Requirements </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.AdditionalRequirements)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Job Location </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.JobLocation)
                        </td>
                    </tr>
                    @{
                        if (Model.IsExperienceRequired != null && (bool) Model.IsExperienceRequired)
                        {
                            <tr>
                                <td style="text-align: right; width: 40%; font-weight: bold">
                                    <strong>Experience </strong>
                                </td>
                                <td style="text-align: left">
                                    @{
                                        if (Model.ExperienceMin != null && Model.ExperienceMin > 0)
                                        {
                                            @Model.ExperienceMin <span>Years</span>
                                        }
                                        else
                                        {
                                            <span>Not Required</span>
                                        }
                                    }
                                   
                                </td>
                            </tr>
                        }
                    }
                    @{
                        if (Model.IsShowSalary != null && (bool) Model.IsShowSalary)
                        {
                            <tr>
                                <td style="text-align: right; width: 40%; font-weight: bold">
                                    <strong>Salary Range </strong>
                                </td>
                                <td style="text-align: left">
                                    @if (!String.IsNullOrEmpty(Model.SalaryRange))
                                    {
                                        <span>$@Model.SalaryRange</span>
                                    }
                                    else if (Model.SalaryMin > 0 && Model.SalaryMax > 0)
                                    {
                                        <span>$@Model.SalaryMin To $@Model.SalaryMax</span>
                                    }
                                    else
                                    {
                                        <span>Negotiable</span>
                                    }
                                </td>
                            </tr>
                        }
                    }
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Salary Details </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.SalaryDetail)
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right; width: 40%; font-weight: bold">
                            <strong>Other Benefit </strong>
                        </td>
                        <td style="text-align: left">
                            @Html.DisplayFor(model => model.OtherBenefit)
                        </td>
                    </tr>
                    </table>
                    @Html.ActionLink("Back to List", "JobManage", "Company", new {@class = "btn btn-primary"})
                    </div>
            }
        }
      

        </div>
    </div>
</div>

Joblanes.Web/Views/Company/JobManage.cshtml
@Styles.Render("~/Content/styledatatable")
@{
    ViewBag.Title = "Jobs";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Web.Joblanes.WebAdminService.JobCategoryDto> jobCategoryList = ViewBag.JobCategoryList;
    List<Web.Joblanes.WebAdminService.JobTypeDto> jobTypeList = ViewBag.JobTypeList;
}

<div class="row" style="padding-right: 10px;">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading custom-panel-h">Manage Job</div>
            <div class="panel-body">
             
                <div class="">
                    <table>
                        <tr class="filteringRow form-group">
                            <th class="form-group">
                                <select name="JobCategory" id="JobCategory" class="form-control">
                                    <option value="0">All Job Category</option>
                                    @{
                                        foreach (var rl in jobCategoryList)
                                        {
                                            <option value="@rl.Id">@rl.Name</option>
                                        }
                                    }
                                </select>
                            </th>
                            <th class="form-group">
                                <select name="JobType" id="JobType" class="form-control">
                                    <option value="0">All Job Type</option>
                                    @{
                                        foreach (var rl in jobTypeList)
                                        {
                                            <option value="@rl.Id">@rl.Name</option>
                                        }
                                    }
                                </select>
                            </th>
                            <th class="form-group">
                                <input id="Title" name="Title" type="text" class="form-control" placeholder="Title"/>
                            </th>
                            <th class="form-group">
                                <select name="Status" id="Status" class="form-control">
                                    <option value="">All</option>
                                    <option value="1">Active</option>
                                    <option value="-1">Inactive</option>
                                </select>
                            </th>
                            <th class="form-group">
                                <input id="pageSize" name="displayPerPage" type="text" class="form-control" placeholder="DisplayPerPage" value="@ViewBag.PageSize"/>
                            </th>
                            <th class="form-group">
                                <input type="button" name="search" id="search" value="View" class="form-control btn-primary"/>
                            </th>
                        </tr>
                    </table>
                    <br/>
                    <table id="DataGrid" class="display table table-striped table-bordered table-condensed table-hover table-responsive" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>Sl.</th>
                            <th>Job Category</th>
                            <th>Job Type</th>
                            <th>Title</th>
                            <th>
                                Status
                            </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody class="text-center"></tbody>
                    </table>
                </div>
                @Html.ActionLink("Create New Job", "JobPosting", "Company", new {@class = "btn btn-primary"})
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/datatable")
    <script type="text/javascript" src="~/Scripts/bootbox.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/Company/ManageJob.js"></script>
}