Joblanes.Web/Models/ViewModel/CompanyDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Web.Joblanes.Models.ViewModel
{
    public class CompanyDetailsViewModel
    {
        public virtual string TradeLicence { get; set; }
        public virtual string WebLink { get; set; }
        public virtual string LinkdinLink { get; set; }
        public virtual string Vision { get; set; }
        public virtual string Mission { get; set; }
        public virtual string Description { get; set; }
        public virtual string Address { get; set; }
        public virtual string Zip { get; set; }
        public virtual string TagLine { get; set; }
        public virtual long Country { get; set; }
        public virtual long State { get; set; }
        public virtual long City { get; set; }
        public virtual long Company { get; set; }     
    }
}

Joblanes.Web/Controllers/JobSeekerController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.ServiceModel;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Model.JobLanes.Dto;
using Model.JobLanes.Entity;
using NHibernate;
using Services.Joblanes;
using Services.Joblanes.Helper;
using Web.Joblanes.Helper;
using Web.Joblanes.Models;
using Web.Joblanes.Models.Dto;
using Web.Joblanes.Models.ViewModel;
using Constants = Web.Joblanes.Context.Constants;
using ImageHelper = Web.Joblanes.Helper.ImageHelper;
using JobSeekerEduVm = Web.Joblanes.Models.ViewModel.JobSeekerEduVm;
using JobSeekerExpVm = Web.Joblanes.Models.ViewModel.JobSeekerExpVm;
using JobSeekerProfileVm = Web.Joblanes.Models.ViewModel.JobSeekerProfileVm;


namespace Web.Joblanes.Controllers
{
    [Authorize]
    [RedirectingAction]
    public class JobSeekerController : Controller
    {

        #region Logger
        readonly log4net.ILog _logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        #endregion

        #region Objects/Properties/Services/Dao & Initialization

        //private readonly IWcfUserService _wcfUserService;
        //private readonly IWebAdminService _webAdminService;
        //private ICompanyAdminService _companyAdminService;
        private readonly CommonHelper _commonHelper;
        private readonly string _aspnetUserId;
        private readonly IUserService _userService;
        private readonly IJobseekerService _jobseekerService;
        private readonly IJobSeekerDetailsService _jobSeekerDetailsService;
        private readonly IJobSeekerEducationalQualificationService _jobSeekerEducationalQualificationService;
        private readonly IJobSeekerExperienceService _jobSeekerExperienceService;
        private readonly IJobSeekerTrainingCoursesService _jobSeekerTrainingCoursesService;
        private readonly IJobPostService _jobPostService;
        private readonly IJobSeekerJobPostService _jobSeekerJobPostService;
        private readonly IJobSeekerCvBankService _jobSeekerCvBankService;
        private readonly IJobSeekerSkillService _jobSeekerSkillService;
        private readonly IRegionService _regionSevice;
        private readonly ICountryService _countryService;
        private readonly IStateService _stateService;
        private readonly ICityService _cityService;
        private readonly IOrganizationTypeService _organizationTypeService;
        private readonly IJobCategoryService _jobCategoryService;
        private readonly ICompanyTypeService _companyTypeService;
        private readonly ICompanyService _companyService;
        public JobSeekerController()
        {
            _aspnetUserId = System.Web.HttpContext.Current.User.Identity.GetUserId().ToString();
            //_wcfUserService = new WcfUserServiceClient();
            //_webAdminService = new WebAdminServiceClient();
            //_companyAdminService = new CompanyAdminServiceClient();
            _commonHelper = new CommonHelper();
            ISession session = NhSessionFactory.OpenSession();
            _userService = new UserService(session);
            
            _jobseekerService = new JobSeekerService(session);
            _jobSeekerDetailsService = new JobSeekerDetailsService(session);
            _jobSeekerEducationalQualificationService = new JobSeekerEducationalQualificationService(session);
            _jobSeekerExperienceService = new JobSeekerExperienceService(session);
            _jobSeekerTrainingCoursesService = new JobSeekerTrainingCoursesService(session);
            _jobPostService = new JobPostService(session);
            _jobSeekerCvBankService = new JobSeekerCvBankService(session);
            _jobSeekerSkillService = new JobSeekerSkillService(session);
            _jobSeekerJobPostService = new JobSeekerJobPostService(session);
            _regionSevice = new RegionService(session);
            _countryService = new CountryService(session);
            _stateService = new StateService(session);
            _cityService = new CityService(session);
            _organizationTypeService = new OrganizationTypeService(session);
            _jobCategoryService = new JobCategoryService(session);
            _companyTypeService = new CompanyTypeService(session);
            _companyService = new CompanyService(session);
        }
        #endregion

        #region Save Methods
        //post methods

        [HttpGet]
        [Authorize(Roles = "Job seekers")]
        public ActionResult BuildResume(int type = 0, string message = "")
        {
            try
            {
                Initialize();
                if (type == 1)
                {
                    ViewBag.SuccessMessage = message;
                }
                else if (type == 2)
                {
                    ViewBag.ErrorMessage = message;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Job seekers")]
        public ActionResult BuildResume(JobSeekerProfileVm profileVm)
        {
            try
            {
                var profileImageUpload = profileVm.ProfileImage;
                //var cvFileUpload = profileVm.Cv;
                var profile = new Model.JobLanes.ViewModel.JobSeekerProfileVm();
                profile.FirstName = profileVm.FirstName;
                profile.LastName = profileVm.LastName;

                /*if any error occured comment this code */
                profile.Linkedin = profileVm.Linkedin;
                profile.MaritalStatus = profileVm.MaritalStatus;
                profile.FatherName = profileVm.FatherName;
                profile.MotherName = profileVm.MotherName;
                profile.Weblink = profileVm.Weblink;
                profile.ZipCode = profileVm.ZipCode;
                profile.Address = profileVm.Address;
                profile.Dob = profileVm.Dob;
                profile.Expertise = profileVm.Expertise;
                profile.Gender = profileVm.Gender;
                /*end */
                profile.RegionId = profileVm.RegionId;
                profile.StateId = profileVm.StateId;
                profile.CityId = profileVm.CityId;
                profile.CountryId = profileVm.CountryId;

                profile.ContactEmail = profileVm.ContactEmail;
                profile.ContactNumber = profileVm.ContactNumber;
                profile.IsPublicResume = profileVm.IsPublicResume;

                if (profileImageUpload != null)
                    profile.ProfileImageBytes = ImageHelper.ConvertFileInByteArray(profileImageUpload.InputStream,
                        profileImageUpload.ContentLength);
                profile.UserProfileId = System.Web.HttpContext.Current.User.Identity.GetUserId().ToString();
                bool issuccess = _jobseekerService.Save(profile);
                if (issuccess)
                    return Json(new Response(true, "Saved Successfully"));
                return Json(new Response(false, "Operation Failed"));
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return Json(new Response(false, ex.Message));
            }
        }

        [HttpGet]
        [Authorize(Roles = "Job seekers")]
        public ActionResult AddProfileInfo()
        {
            try
            {
                // var aspnetUserId = System.Web.HttpContext.Current.User.Identity.GetUserId().ToString();
                var jobSeekerProfileDto = _jobseekerService.GetJobSeekerProfileData(_aspnetUserId);
                JobSeekerProfileVm destObject = new JobSeekerProfileVm();
                if (jobSeekerProfileDto != null)
                {
                    CopyClass.CopyObject<JobSeekerProfileVm>(jobSeekerProfileDto, ref destObject);
                }
                if (jobSeekerProfileDto != null)
                {
                    ViewBag.GenderList = new SelectList(_commonHelper.LoadEmumToDictionary<Constants.Gender>(), "Key", "Value", jobSeekerProfileDto.Gender).ToList();
                    ViewBag.MaritalList = new SelectList(_commonHelper.LoadEmumToDictionary<Constants.MaritalType>(), "Key", "Value", jobSeekerProfileDto.MaritalStatus).ToList();
                    ViewBag.RegionList = new SelectList(_regionSevice.LoadRegion(0, int.MaxValue, "", "", "", 1), "Id", "Name", jobSeekerProfileDto.RegionId);
                    if (!String.IsNullOrEmpty(destObject.ContactNumber))
                    {
                        ViewBag.CountryList = new SelectList(_countryService.LoadCountry(0, int.MaxValue, "", "", "", "", "", destObject.RegionId, 1), "Id", "Name", jobSeekerProfileDto.CountryId);
                        ViewBag.StateList = new SelectList(_stateService.LoadState(0, int.MaxValue, "", "", "", "", destObject.RegionId, destObject.CountryId, 1), "Id", "Name", jobSeekerProfileDto.StateId);
                        ViewBag.CityList = new SelectList(_cityService.LoadCity(0, int.MaxValue, "", "", "", "", destObject.RegionId, destObject.CountryId, destObject.StateId, 1), "Id", "Name", jobSeekerProfileDto.CityId);
                    }
                    else
                    {
                        ViewBag.CountryList = new SelectList(String.Empty, "Value", "Text");
                        ViewBag.StateList = new SelectList(String.Empty, "Value", "Text");
                        ViewBag.CityList = new SelectList(String.Empty, "Value", "Text");
                    }
                }
                else
                {
                    Initialize();
                }
                destObject.ContactEmail = System.Web.HttpContext.Current.User.Identity.Name;

Joblanes.Web/Views/JobSeeker/AddEducationalQualification.cshtml
@model Web.Joblanes.Models.ViewModel.JobSeekerEduVm
    @Styles.Render("~/Content/bootstrap-datetimepicker")
    @{
        ViewBag.Title = "AddEducationalQualification";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <div class="panel panel-default">
        <div class="panel-heading">Add Educational Qualification</div>
        <div class="panel-body">

            @using (Html.BeginForm("AddEducationalQualification", "JobSeeker"))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @Html.LabelFor(model => model.Degree, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Degree, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Degree, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Institute, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Institute, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Institute, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.StartingYear, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StartingYear, new { htmlAttributes = new { @class = "form-control form_datetime", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.StartingYear, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PassingYear, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PassingYear, new { htmlAttributes = new { @class = "form-control form_datetime", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.PassingYear, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Result, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Result, new { htmlAttributes = new { @class = "form-control numbersOnly" } })
                            @Html.ValidationMessageFor(model => model.Result, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Add" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/bootstrap-datetimepicker")
        <script src="~/Scripts/jquery.blockUI.js"></script>
        <script src="~/Scripts/Common.js"></script>
        <script src="~/Scripts/Jobseekerjs/jobseeker.js"></script>
        <script type="text/javascript">
            $(document).on("focus", "input.form_datetime", function () {
                var today = new Date();
                var initialDate = today.getFullYear().toString() + "-" + (today.getMonth() + 1) + "-" + today.getDate().toString();
                var startDate = today.getFullYear().toString() + "-" + (1) + "-" + "01";
                //var startDate = new Date();
                var endDate = initialDate;
                $(this).datetimepicker({
                    format: "yyyy-mm-dd",
                    //autoclose: true,
                    //todayBtn: false,
                    //showMeridian: true,
                    initialDate: initialDate,
                    //startDate: startDate,
                    //endDate: endDate,
                    startView: 2,
                    minView: 2,
                    maxView: 4
                }).on('changeDate', function (ev) {
                    $(this).removeClass("highlight");
                });
            });
        </script>
    }

Joblanes.Web/Views/JobSeeker/AddExperience.cshtml
@using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder
@model Web.Joblanes.Models.ViewModel.JobSeekerExpVm
@Styles.Render("~/Content/bootstrap-datetimepicker")
@{
    ViewBag.Title = "AddExperience";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">Add Experience</div>
    <div class="panel-body">

        @using (Html.BeginForm("AddExperience", "JobSeeker"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
            @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.CompanyName, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CompanyAddress, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CompanyAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanyAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Designation, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateFrom, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control form_datetime", @readonly = "readonly"} })
                        @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateTo, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control form_datetime", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.DateTo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Responsibility, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Responsibility,new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Responsibility, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsCurrent, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(model => model.IsCurrent, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IsCurrent, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Add" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    <script src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/Common.js"></script>
    <script src="~/Scripts/Jobseekerjs/jobseeker.js"></script>
    <script type="text/javascript">
        $(document).on("focus", "input.form_datetime", function () {
            var today = new Date();
            var initialDate = today.getFullYear().toString() + "-" + (today.getMonth() + 1) + "-" + today.getDate().toString();
            var startDate = today.getFullYear().toString() + "-" + (1) + "-" + "01";
            //var startDate = new Date();
            var endDate = initialDate;
            $(this).datetimepicker({
                format: "yyyy-mm-dd",
                //autoclose: true,
                //todayBtn: false,
                //showMeridian: true,
                initialDate: initialDate,
                //startDate: startDate,
                //endDate: endDate,
                startView: 2,
                minView: 2,
                maxView: 4
            }).on('changeDate', function (ev) {
                $(this).removeClass("highlight");
            });
        });
    </script>
}

Joblanes.Web/Views/JobSeeker/AddTraining.cshtml
@model Web.Joblanes.Models.ViewModel.JobSeekerTrainingVm
@Styles.Render("~/Content/bootstrap-datetimepicker")
@{
    ViewBag.Title = "AddTraining";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">Add Training </div>
    <div class="panel-body">

        @using (Html.BeginForm("AddTraining", "JobSeeker"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Institute, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Institute, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Institute, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control form_datetime", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CloseDate, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CloseDate, new { htmlAttributes = new { @class = "form-control form_datetime", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.CloseDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Add" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    <script src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/Common.js"></script>
    <script src="~/Scripts/Jobseekerjs/jobseeker.js"></script>
    <script type="text/javascript">
        $(document).on("focus", "input.form_datetime", function () {
            var today = new Date();
            var initialDate = today.getFullYear().toString() + "-" + (today.getMonth() + 1) + "-" + today.getDate().toString();
            var startDate = today.getFullYear().toString() + "-" + (1) + "-" + "01";
            //var startDate = new Date();
            var endDate = initialDate;
            $(this).datetimepicker({
                format: "yyyy-mm-dd",
                //autoclose: true,
                //todayBtn: false,
                //showMeridian: true,
                initialDate: initialDate,
                //startDate: startDate,
                //endDate: endDate,
                startView: 2,
                minView: 2,
                maxView: 4
            }).on('changeDate', function (ev) {
                $(this).removeClass("highlight");
            });
        });
    </script>
}

Joblanes.Web/Views/JobSeeker/BuildResume.cshtml
@model Web.Joblanes.Models.ViewModel.JobSeekerProfileVm
@Styles.Render("~/Content/bootstrap-datetimepicker")
@{
    ViewBag.Title = "BuildResume";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #inner {
        width: 50%;
        margin: 0 auto;
    }
</style>
<div id="outer" style="width:100%">
    <div id="inner">
        <div id="profile">
            @Html.Action("AddProfileInfo", "JobSeeker")
        </div>
    </div>
</div>


@*<div class="row">
        <div class="col-md-6">
            @Html.Action("AddProfileInfo", "JobSeeker")
        </div>
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    <script src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/Common.js"></script>
    <script src="~/Scripts/Jobseekerjs/jobseeker.js"></script>
    <script type="text/javascript">
        $(document).on("focus", "input.form_datetime", function () {
            var today = new Date();
            var initialDate = today.getFullYear().toString() + "-" + (today.getMonth() + 1) + "-" + today.getDate().toString();
            var startDate = today.getFullYear().toString() + "-" + (1) + "-" + "01";
            //var startDate = new Date();
            var endDate = initialDate;
            $(this).datetimepicker({
                format: "yyyy-mm-dd",
                //autoclose: true,
                //todayBtn: false,
                //showMeridian: true,
                initialDate: initialDate,
                //startDate: startDate,
                //endDate: endDate,
                startView: 2,
                minView: 2,
                maxView: 4
            }).on('changeDate', function (ev) {
                $(this).removeClass("highlight");
            });
        });
    </script>

}

Joblanes.Web/Views/JobSeeker/OnlineApplication.cshtml
@{
    ViewBag.Title = "BrowseJob";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/styledatatable")

<style type="text/css">
    #inner {
        width: 70%;
        margin: 0 auto;
    }

    .custom {
        width: 200px !important;
    }
</style>


<div id="outer" style="width:100%">
    <div id="inner">
        <div class="panel panel-default">
            <div class="panel-heading"> My Applied Jobs</div>
            <div class="panel-body">
                @*<table>
                    <tr class="form-group">
                        <th>&nbsp;</th>
                        <th class="form-group">
                            @Html.DropDownList("jobCategoryId", (IEnumerable<SelectListItem>)ViewBag.JobCategory, "--Category--", new { @class = "form-control" })
                        </th>
                        <th class="form-group">
                            <input id="PageSize" name="displayPerPage" type="text" class="form-control" placeholder="DisplayPerPage" value="@ViewBag.PageSize" />
                        </th>
                        <th class="form-group">
                            <input type="button" name="search" id="search" value="Show" class="form-control btn btn-primary" />
                        </th>
                    </tr>
                </table>*@
                <br />
                @*table-striped table-bordered table-condensed table-hover table-responsive*@
                <table id="DataGrid" class="table table-hover table-responsive table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>

                            </th>
                        </tr>
                    </thead>
                    <tbody class="text-center"></tbody>
                </table>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/datatable")
    <script type="text/javascript" src="~/Scripts/jquery.blockUI.js"></script>
    <script type="text/javascript">
        function dataTableRender() {
            var pageSize = 10;
            if ($('#PageSize').val() != "" && /^\d+$/.test($('#PageSize').val())) {
                pageSize = parseInt($('#PageSize').val());
            } else {
                $('#PageSize').val(pageSize);
            }
            $('#DataGrid').dataTable({
                destroy: true,
                "processing": true,
                searching: false,
                serverSide: true,
                "scrollX": true,
                "bLengthChange": false,
                "iDisplayLength": pageSize,
                "bSort": false,
                ajax: {
                    url: '@Url.Action("BrowseJobSeeekerJob", "JobSeeker")',
                    type: 'POST',
                    data: function (d) {
                        //d.jobCategoryId = $('#jobCategoryId').val();
                    }
                }
            });
        }

        $(document).ready(function () {
            dataTableRender();

            $(document).on("click", "#search", function () {
                dataTableRender();
            });
        });

    </script>
}