Joblanes.Web/Models/ViewModel/JobCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Web.Joblanes.Models.ViewModel
{
    public class JobCategoryViewModel
    {
        public virtual long Id { get; set; }
        [Required]
        public virtual string Name { get; set; }
        public virtual int Status { get; set; }
        public virtual string Description { get; set; } 
    }
}

Joblanes.Web/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Model.JobLanes.Dto;
using NHibernate;
using Services.Joblanes;
using Services.Joblanes.Helper;
using Web.Joblanes.Helper;


namespace Web.Joblanes.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        #region Logger
        readonly log4net.ILog _logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        #endregion

        #region Objects/Properties/Services/Dao & Initialization

        //private readonly IWcfUserService _wcfUserService;
        //private readonly IWebAdminService _webAdminService;
        //private ICompanyAdminService _companyAdminService;
        private readonly CommonHelper _commonHelper;
        private readonly IJobseekerService _jobseekerService;
        private readonly IJobSeekerDetailsService _jobSeekerDetailsService;
        private readonly IJobSeekerEducationalQualificationService _jobSeekerEducationalQualificationService;
        private readonly IJobSeekerExperienceService _jobSeekerExperienceService;
        private readonly IJobSeekerTrainingCoursesService _jobSeekerTrainingCoursesService;
        private readonly IJobPostService _jobPostService;
        private readonly IJobSeekerJobPostService _jobSeekerJobPostService;
        private readonly IJobSeekerCvBankService _jobSeekerCvBankService;
        private readonly IJobSeekerSkillService _jobSeekerSkillService;
        private readonly IRegionService _regionSevice;
        private readonly ICountryService _countryService;
        private readonly IStateService _stateService;
        private readonly ICityService _cityService;
        private readonly IOrganizationTypeService _organizationTypeService;
        private readonly IJobCategoryService _jobCategoryService;
        private readonly IJobTypeService _jobTypeService;
        private readonly ICompanyService _companyService;
        public JobsController()
        {
            _commonHelper = new CommonHelper();
          //  _wcfUserService = new WcfUserServiceClient();
          //_webAdminService = new WebAdminServiceClient();
          //  _companyAdminService = new CompanyAdminServiceClient();
            ISession session = NhSessionFactory.OpenSession();
           _jobseekerService = new JobSeekerService(session);
            _jobSeekerDetailsService = new JobSeekerDetailsService(session);
            _jobSeekerEducationalQualificationService = new JobSeekerEducationalQualificationService(session);
            _jobSeekerExperienceService = new JobSeekerExperienceService(session);
            _jobSeekerTrainingCoursesService = new JobSeekerTrainingCoursesService(session);
            _jobPostService = new JobPostService(session);
            _jobSeekerCvBankService = new JobSeekerCvBankService(session);
            _jobSeekerSkillService = new JobSeekerSkillService(session);
            _jobSeekerJobPostService = new JobSeekerJobPostService(session);
            _regionSevice = new RegionService(session);
            _countryService = new CountryService(session);
            _stateService = new StateService(session);
            _cityService = new CityService(session);
            _organizationTypeService = new OrganizationTypeService(session);
            _jobCategoryService = new JobCategoryService(session);
            _jobTypeService = new JobTypeService(session);
            _companyService = new CompanyService(session);
        }
        #endregion

        #region Browse Job
        [AllowAnonymous]
        public ActionResult BrowseJob(string what = "")
        {
            try
            {
                Initialize();
                if (!String.IsNullOrEmpty(what))
                {
                    var ary = what.Split(new[] { "_??!_" }, StringSplitOptions.None);
                    what = ary[0];
                    var where = ary[1];
                    ViewBag.what = what;
                    ViewBag.where = where;
                }
                return View();
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                throw;
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult BrowseJobPost(int draw, int start, int length, string orderBy, string orderDir, string what = "",
            string where = "", int ageRangeFrom = 0, int ageRangeTo = 0, int expRangeFrom = 0, int expRangeTo = 0,
            int salaryRangeFrom = 0, int salaryRangeTo = 0, long[] company = null, long[] jobCategory = null, long[] jobType = null)
        {
            try
            {
                IList<JobPostsDto> jobList = _jobPostService.LoadJobPost(start, length, "", "", what, where, ageRangeFrom, ageRangeTo, expRangeFrom, expRangeTo, salaryRangeFrom, salaryRangeTo, company, jobCategory, jobType);
                int recordsTotal = _jobPostService.CountJobPost(what, where, ageRangeFrom, ageRangeTo, expRangeFrom, expRangeTo, salaryRangeFrom, salaryRangeTo, company, jobCategory, jobType);
                var data = new List<object>();
                foreach (var dto in jobList)
                {
                    dto.JobDescription = GetJobDescription(dto.JobDescription);
                    var str = new List<string>();
                    if (dto.DeadLine != null)
                    {
                        var job = ConvertPartialViewToString(PartialView("_jobItem", dto));
                        str.Add(job);
                        data.Add(str);
                    }


                }
                return Json(new
                {
                    draw = draw,
                    recordsTotal = recordsTotal,
                    recordsFiltered = recordsTotal,
                    start = start,
                    length = length,
                    data = data
                });

            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                throw;
            }
        }

        private string GetJobDescription(string description)
        {
            if (String.IsNullOrEmpty(description)) return "";
            var len = description.Length;
            if (len < 200) return description;
            return description.Substring(0, 199);
        }
        [AllowAnonymous]
        public ActionResult JobPostDetail(long id)
        {
            try
            {
                if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    var userId = System.Web.HttpContext.Current.User.Identity.GetUserId().ToString();
                    JobPostsDto jobPostDto = _jobPostService.GetById(id, userId, true);
                    //var jobcategory = _webAdminService.GetJobCategoryById(jobPostDto.JobCategory);
                    return View(jobPostDto);
                }
                else
                {
                    JobPostsDto jobPostDto = _jobPostService.GetById(id);
                    return View(jobPostDto);
                }
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                throw;
            }
        }


        #endregion

        #region Helper
        protected string ConvertPartialViewToString(PartialViewResult partialView)
        {
            using (var sw = new StringWriter())
            {
                partialView.View = ViewEngines.Engines
                  .FindPartialView(ControllerContext, partialView.ViewName).View;

                var vc = new ViewContext(
                  ControllerContext, partialView.View, partialView.ViewData, partialView.TempData, sw);
                partialView.View.Render(vc, sw);

                var partialViewString = sw.GetStringBuilder().ToString();

                return partialViewString;
            }
        }
        private void Initialize()
        {
            ViewBag.GenderList = new SelectList(_commonHelper.LoadEmumToDictionary<Web.Joblanes.Context.Constants.Gender>(), "Key", "Value").ToList();
            ViewBag.MaritalList = new SelectList(_commonHelper.LoadEmumToDictionary<Web.Joblanes.Context.Constants.MaritalType>(), "Key", "Value").ToList();

            ViewBag.RegionList = new SelectList(_regionSevice.LoadRegion(0, int.MaxValue, "", "", "", 1), "Id", "Name");
            ViewBag.CountryList = new SelectList(String.Empty, "Value", "Text");
            ViewBag.StateList = new SelectList(String.Empty, "Value", "Text");
            ViewBag.CityList = new SelectList(String.Empty, "Value", "Text");
            ViewBag.JobCategory = new SelectList(_jobCategoryService.LoadJobCategory(1), "Id", "Name");
            ViewBag.jobType = new SelectList(_jobTypeService.LoadJobType(0, int.MaxValue - 2, "", "", "", 1), "Id", "Name");
        }
        #endregion

        #region Home Page

        [AllowAnonymous]
        [HttpGet]
        public ActionResult FeaturedJobs()
        {
            try
            {
                IList<CompanyDto> companyDto = _companyService.LoadCompany(1, 0, "", 0, 0, 0, 0);
                return PartialView("_featuredJob", companyDto);

            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                throw;
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult LatestJob()
        {
            try
            {
                IList<JobPostsDto> jobList = _jobPostService.LoadJobPost(0, 10, "CreationDate", "desc", "", "", 0, 0, 0, 0, 0, 0, null, null, null);
                foreach (var dto in jobList)
                {
                    dto.JobDescription = GetJobDescription(dto.JobDescription);
                }
                return PartialView("_latestJob", jobList);
            }
            catch (Exception ex)
            {

Joblanes.Web/Views/Jobs/BrowseJob.cshtml
@using SelectListItem = System.Web.WebPages.Html.SelectListItem
@model Model.JobLanes.Dto.JobPostsDto

@{
    ViewBag.Title = "BrowseJob";
    Layout = "~/Views/Shared/_LayoutWide.cshtml";
    string col = "9";
}
@Styles.Render("~/Content/styledatatable")
@Styles.Render("~/Content/bootstrap-multiselect")
<style type="text/css">
    #inner {
        width: 50%;
        margin: 0 auto;
    }

    .custom {
        width: 200px !important;
    }

    .AgeFilter {
        display: none;
    }

    .SalaryFilter {
        display: none;
    }

    .ExpFilter {
        display: none;
    }
</style>
<div class="row">
    <div class="col-md-3 col-sm-3  " role="navigation">
        <div class="panel panel-primary">
            <div class="panel-heading">Job Filtering</div>
            <div class="panel-body">
                <div class="form-horizontal">


                    <div class="form-group">
                        <div class="col-md-12">
                            <span>Job Category</span>
                            @Html.DropDownList("jobCat", (IEnumerable<System.Web.Mvc.SelectListItem>)ViewBag.JobCategory, new { @class = "form-control", @id = "jobCat", @multiple = "multiple" })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-md-12">
                            <span>Job Type</span>
                            @Html.DropDownList("jobTyp", (IEnumerable<System.Web.Mvc.SelectListItem>)ViewBag.jobType, new { @class = "form-control", @id = "jobTyp", @multiple = "multiple" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="checkbox">
                                <label class="">
                                    <input class="isAgeFilter" value="" type="checkbox"> Filter Result with age
                                </label>
                            </div>
                        </div>

                    </div>
                    <div class="AgeFilter">
                        <span> Age Range</span>
                        <div class="form-group">

                            <div class="col-md-6">
                                <input type="text" class="form-control numbersOnly" id="minAge" placeholder="Min. Age">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control numbersOnly" id="maxAge" placeholder="Max. Age">
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="checkbox">
                                <label>
                                    <input class="isExpFilter" value="" type="checkbox"> Filter Result with Experience
                                </label>
                            </div>
                        </div>

                    </div>
                    <div class="ExpFilter">
                        <span> Experience Range</span>
                        <div class="form-group">

                            <div class="col-md-6">
                                <input type="text" class="form-control numbersOnly" id="minExp" placeholder="Min. Exp">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control numbersOnly" id="maxExp" placeholder="Max. Exp">
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="checkbox">
                                <label>
                                    <input class="isSalaryFilter" value="" type="checkbox"> Filter Result with Salary
                                </label>
                            </div>
                        </div>

                    </div>
                    <div class="SalaryFilter">
                        <span> Salary Range</span>
                        <div class="form-group">
                            <div class="col-md-6">
                                <input type="text" class="form-control numbersOnly" id="minSalary" placeholder="Min. Salary">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control numbersOnly" id="maxSalary" placeholder="Max. Salary">
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" class="btn btn-primary col-md-offset-5" id="filter" value="Search" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-md-9  col-sm-9">
        <div class="panel panel-primary">
            @*<div class="panel-heading custom-panel-h"> Company Profile</div>*@
            <div class="panel-body">
                <div class="row no-margin">
                    <table>
                        <tr class="form-group">
                            <th>&nbsp;</th>
                            @if (ViewBag.what != null)
                            {
                                <th class="form-group">
                                    <span>What</span>
                                    <input type="text" class="form-control" id="what" value="@ViewBag.what" placeholder="type desired jobs" />
                                </th>
                            }
                            else
                            {
                                <th class="form-group">
                                    <span>What</span>
                                    <input type="text" class="form-control" id="what" placeholder="type desired jobs" />
                                </th>
                            }
                            @if (ViewBag.where != null)
                            {

                                <th class="form-group">
                                    <span>Where</span>
                                    <input type="text" class="form-control" id="where" value="@ViewBag.where" placeholder="city state or joblocation" />
                                </th>
                            }
                            else
                            {

                                <th class="form-group">
                                    <span>Where</span>
                                    <input type="text" class="form-control" id="where" placeholder="city state or joblocation" />
                                </th>
                            }
                            @*<th class="form-group">
                                    @Html.DropDownList("jobCategoryId", (IEnumerable<SelectListItem>)ViewBag.JobCategory, "--Category--", new { @class = "form-control" })
                                </th>*@
                            <th class="form-group">
                                <span>&nbsp;</span>
                                <input id="PageSize" name="displayPerPage" type="text" class="form-control" placeholder="DisplayPerPage" value="@ViewBag.PageSize" />
                            </th>
                            <th class="form-group">
                                <span>&nbsp;</span>
                                <input type="button" name="search" id="search" value="Show" class="form-control btn btn-primary" />
                            </th>
                        </tr>
                    </table>
                    <br />
                    <table id="DataGrid" class="table table-hover table-responsive table-inverse table-search table-striped table-td-valign-middle" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>

                                </th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>


            </div>
        </div>
    </div>

    
</div>
@section Scripts {
    @Scripts.Render("~/bundles/datatable")
    @Scripts.Render("~/bundles/bootstrap-multiselect")
    <script type="text/javascript" src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/Common.js"></script>
    <script src="~/Scripts/Jobseekerjs/jobseeker.js"></script>
    <script type="text/javascript">
        function dataTableRender() {
            var pageSize = 10;
            if ($('#PageSize').val() != "" && /^\d+$/.test($('#PageSize').val())) {
                pageSize = parseInt($('#PageSize').val());
            } else {
                $('#PageSize').val(pageSize);
            }
            $('#DataGrid').dataTable({
                destroy: true,
                "processing": true,
                searching: false,
                serverSide: true,
                "scrollX": true,
                "bLengthChange": false,
                "iDisplayLength": pageSize,
                "bSort": false,
                ajax: {
                    url: '@Url.Action("BrowseJobPost", "Jobs")',
                    type: 'POST',
                    data: function (d) {
                        d.what = $("#what").val();
                        d.where = $("#where").val();
                        d.ageRangeFrom = $("#minAge").val();
                        d.ageRangeTo = $("#maxAge").val();
                        d.expRangeFrom = $("#minExp").val();
                        d.expRangeTo = $("#maxExp").val();
                        d.salaryRangeFrom = $("#minSalary").val();
                        d.salaryRangeTo = $("#maxSalary").val();
                        d.company = null;
                        d.jobCategory = $("#jobCat").val(),
                            d.jobType = $("#jobTyp").val();

                    }
                }
            });
        }

        //function muliselectfnc(holder) {
        //    $(holder).multiselect({
        //        enableFiltering: true,
        //        includeSelectAllOption: true,
        //        numberDisplayed: 2,
        //        maxHeight: 500,
        //        buttonWidth: '100%',
        //        nonSelectedText: 'All'
        //    });
        //    }

        //$(document).ready(function () {
        //    muliselectfnc($('#jobCat'));
        //    muliselectfnc($('#jobTyp'));
        //});

        $(document).ready(function () {
            $(document).on("click", ".isAgeFilter", function () {
                if ($(".isAgeFilter").prop("checked") == true) {
                    $(".AgeFilter").show();
                } else {
                    $(".AgeFilter").hide();
                    $("#minAge").val("");
                    $("#maxAge").val("");
                    dataTableRender();
                }
            });
            $(document).on("click", ".isExpFilter", function () {
                if ($(".isExpFilter").prop("checked") == true) {
                    $(".ExpFilter").show();
                } else {
                    $(".ExpFilter").hide();
                    $("#minExp").val("");
                    $("#maxExp").val("");
                    dataTableRender();
                }
            });
            $(document).on("click", ".isSalaryFilter", function () {
                if ($(".isSalaryFilter").prop("checked") == true) {
                    $(".SalaryFilter").show();
                } else {
                    $(".SalaryFilter").hide();
                    $("#minSalary").val("");
                    $("#maxSalary").val("");
                    dataTableRender();
                }
            });
            // .isExpFilter .isSalaryFilter
            dataTableRender();
            $(document).on("click", "#filter", function () {
                dataTableRender();
            });
            $(document).on("click", "#search", function () {
                dataTableRender();
            });
        });

    </script>
}

Joblanes.Web/Views/Jobs/CompanyJobs.cshtml
@using SelectListItem = System.Web.WebPages.Html.SelectListItem
@model Model.JobLanes.Dto.JobPostsDto

@{
    ViewBag.Title = "CompanyJobs";
    Layout = "~/Views/Shared/_LayoutWide.cshtml";
    string col = "9";
}
@Styles.Render("~/Content/styledatatable")
<style type="text/css">
    #inner {
        width: 50%;
        margin: 0 auto;
    }

    .custom {
        width: 200px !important;
    }
</style>
<div class="row" style="margin-left: 2%;">
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        if (HttpContext.Current.User.IsInRole("Web Admin") || HttpContext.Current.User.IsInRole("Employers"))
        {
            <div class="col-md-3 no-padding">
                @Html.Partial("_sidebar")
            </div>
            col = "6";
        }
    }
    <div class="col-md-@col no-padding">
        <div class="panel panel-primary">
            <div class="panel-heading">Jobs From <strong>@ViewBag.companyName</strong> </div>
            <div class="panel-body">
                <div class="row no-margin">
                    <table>
                        <tr class="form-group">
                            <th>&nbsp;</th>
                            <th class="form-group">
                                <input id="PageSize" name="displayPerPage" type="text" class="form-control" placeholder="DisplayPerPage" value="@ViewBag.PageSize" />
                            </th>
                            <th class="form-group">
                                <input type="button" name="search" id="search" value="Show" class="form-control btn btn-primary" />
                            </th>
                        </tr>
                    </table>
                    <br />
                    <table id="DataGrid" class="table table-hover table-responsive table-inverse table-search table-striped table-td-valign-middle" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>

                                </th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
@section Scripts {
    @Scripts.Render("~/bundles/datatable")
    <script type="text/javascript" src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/Common.js"></script>
    <script src="~/Scripts/Jobseekerjs/jobseeker.js"></script>
    <script type="text/javascript">
        function dataTableRender() {
            var pageSize = 10;
            if ($('#PageSize').val() != "" && /^\d+$/.test($('#PageSize').val())) {
                pageSize = parseInt($('#PageSize').val());
            } else {
                $('#PageSize').val(pageSize);
            }
            $('#DataGrid').dataTable({
                destroy: true,
                "processing": true,
                searching: false,
                serverSide: true,
                "scrollX": true,
                "bLengthChange": false,
                "iDisplayLength": pageSize,
                "bSort": false,
                ajax: {
                    url: '@Url.Action("CompanyJobsPost", "Jobs")',
                    type: 'POST',
                    data: function (d) {
                        d.id = @ViewBag.companyId;
                    }
                }
            });
        }

        $(document).ready(function () {
            dataTableRender();
            $(document).on("click", "#search", function () {
                dataTableRender();
            });
        });

    </script>
}

Joblanes.Web/Views/Jobs/JobCategoryJobs.cshtml
@using SelectListItem = System.Web.WebPages.Html.SelectListItem
@model Model.JobLanes.Dto.JobPostsDto

@{
    ViewBag.Title = "JobCategoryJobs";
    Layout = "~/Views/Shared/_LayoutWide.cshtml";
    string col = "9";
}
@Styles.Render("~/Content/styledatatable")
<style type="text/css">
    #inner {
        width: 50%;
        margin: 0 auto;
    }

    .custom {
        width: 200px !important;
    }
</style>
<div class="row" style="margin-left: 2%;">
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        if (HttpContext.Current.User.IsInRole("Web Admin") || HttpContext.Current.User.IsInRole("Employers"))
        {
            <div class="col-md-3 no-padding">
                @Html.Partial("_sidebar")
            </div>
            col = "6";
        }
    }
    <div class="col-md-@col no-padding">
        <div class="panel panel-primary">
            <div class="panel-heading">Jobs From <strong>@ViewBag.categoryName</strong> category</div>
            <div class="panel-body">
                <div class="row no-margin">
                    <table>
                        <tr class="form-group">
                            <th>&nbsp;</th>
                            <th class="form-group">
                                <input id="PageSize" name="displayPerPage" type="text" class="form-control" placeholder="DisplayPerPage" value="@ViewBag.PageSize" />
                            </th>
                            <th class="form-group">
                                <input type="button" name="search" id="search" value="Show" class="form-control btn btn-primary" />
                            </th>
                        </tr>
                    </table>
                    <br />
                    <table id="DataGrid" class="table table-hover table-responsive table-inverse table-search table-striped table-td-valign-middle" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>

                                </th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
@section Scripts {
    @Scripts.Render("~/bundles/datatable")
    <script type="text/javascript" src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/Common.js"></script>
    <script src="~/Scripts/Jobseekerjs/jobseeker.js"></script>
    <script type="text/javascript">
        function dataTableRender() {
            var pageSize = 10;
            if ($('#PageSize').val() != "" && /^\d+$/.test($('#PageSize').val())) {
                pageSize = parseInt($('#PageSize').val());
            } else {
                $('#PageSize').val(pageSize);
            }
            $('#DataGrid').dataTable({
                destroy: true,
                "processing": true,
                searching: false,
                serverSide: true,
                "scrollX": true,
                "bLengthChange": false,
                "iDisplayLength": pageSize,
                "bSort": false,
                ajax: {
                    url: '@Url.Action("JobCategoryJobsPost", "Jobs")',
                    type: 'POST',
                    data: function (d) {
                        d.id = @ViewBag.jobcategoryId;
                    }
                }
            });
        }

        $(document).ready(function () {
            dataTableRender();
            $(document).on("click", "#search", function () {
                dataTableRender();
            });
        });

    </script>
}

Joblanes.Web/Views/Jobs/_featuredJob.cshtml
@using Model.JobLanes.Dto
@model IEnumerable<Model.JobLanes.Dto.CompanyDto>


<div class="col-lg-12 content-box ">

    <div class="row row-featured row-featured-category row-featured-company">
        <div class="col-lg-12  box-title no-border">
            <div class="inner">
                <h2>
                    <span>Featured</span>
                    companies <a class="sell-your-item" href="#"> See all companies <i class="  icon-th-list"></i> </a>
                </h2>
            </div>
        </div>
        @foreach (CompanyDto companyDto in Model)
        {
            var imgSrc = "/images/jobs/NoLogo.png";
            if (companyDto.Logo != null && companyDto.Logo.Length > 0)
            {
                var base64 = Convert.ToBase64String(companyDto.Logo);
                imgSrc = String.Format("data:image/gif;base64,{0}", base64);

            }
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6 f-category">
                <a href="@Url.Action("CompanyJobs", "Jobs", new { id = companyDto.Id })">
                <img alt="img" class="img-responsive" src="@imgSrc">
                <h6>
                Jobs at <span class="company-name">@companyDto.Name</span> <span class="jobs-count text-muted"></span>
                </h6>
                </a>
            </div>
        }


    </div>
</div>